name = input("What is your name? ")
age = input("How old are you? ")
hobby = input("What is your favorite hobby? ")
print("Welcome " + name + "!")
print("You are " + age + " years old and love " + hobby + ".")
